baseURL: 'https://example.org/'
languageCode: 'en-us'
title: 'Hugo React Bootstrap5 Typescript Esbuild Netlify Template'
enableGitInfo: true

module:
  mounts:
    - source: "assets"
      target: "assets"
    - source: "static"
      target: "static"
    - source: "node_modules/bootstrap"
      target: "assets/scss/bootstrap"
    - source: "node_modules"
      target: "static/js"
    - source: "node_modules/@fortawesome/fontawesome-free"
      target: "static"
    - source: "node_modules"
      target: "assets/css"
    - source: "node_modules/@fortawesome/fontawesome-free/scss"
      target: "assets/css"
      
menus:
  main:
    - identifier: "Home"
      name: "Home"
      url: "/"
      weight: 100
    - identifier: "Shop"
      name: "Shop"
      url: "/shop"
      weight: 200

  footer:
     - identifier: "About"
       name: "About"
       url: "/about"
       weight: 500

